# Generated by Django 3.0.7 on 2025-09-26 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20250925_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
